language: c

install:
  - source devtools/ci/install.sh
  - export PYTHONUNBUFFERED=true

script:
  - export CC="gcc -std=c89"
  - source deactivate
  - conda install --yes conda-build
  - conda build devtools/conda-recipe
  - source activate $python
  - conda install $HOME/miniconda/conda-bld/linux-64/openmm-testsystems-dev-*
  - conda list -e
  - nosetests -vv

env:
  matrix:
    - python=2.7  CONDA_PY=27
    # - python=3.3  CONDA_PY=33

  global:
    # encrypted BINSTAR_TOKEN for push of dev package to binstar
    - secure: "HvroLIlN+DZJYdE3SvL3fy9z96b2LLl5nClveLduioGHZNScFnmlnDf9maKZQw0p2eqV/LPsYVuiU66+oyWuym0UuqAo19zfCg63HWAJ/zEdGYu2gxz0eNZq3oL1lDjbS+R/4tfCpudRXjUh2MUgYfXii6DHKBm48lBgHOFuYo4="

after_success:
  - echo "after_success"
  - source devtools/ci/after_sucess.sh
