package:
  name: openmmtools
  version: 0.0.0

#source:
#  fn: master.zip
#  url: https://github.com/choderalab/openmmtools/archive/master.zip

requirements:
  build:
    - python
    - cython
    - numpy
    - scipy
    - nose
    - setuptools
    - openmm
    - jinja2

  run:
    - python
    - scipy
    - openmm
    - nose
    - setuptools
    - jinja2


  test:
    requires:
      - nose
    imports:
      - openmmtools
    commands:
      - nosetests openmmtools --with-doctest --verbosity=2 --nocapture

build:
  # Preserve the Python egg directory. This is needed for some packages
  # that use setuptools specific features.
  preserve_egg_dir: yes # (default no)

about:
  home: https://github.com/choderalab/openmmtools
  license: GNU Lesser General Public License v2 or later (LGPLv2+)
