package:
  name: openmmtools-dev
  version: 0.0.0

source:
  path: ../../

build:
  preserve_egg_dir: True
  number: 0

requirements:
  build:
    - python
#    - cython
#    - numpy
#    - scipy
    - setuptools
    - openmm
#    - parmed
#    - mdtraj
#    - netcdf4
#    - pyyaml

  run:
    - python
    - numpy
    - scipy
    - six
    - openmm >=7.2
    - parmed
    - mdtraj
    - pyyaml
    # NetCDF4 on windows conda has DLL issues, so pin libnetcdf. Remove this later
    - netcdf4 # [not win]
    - netcdf4 ==1.4.0=py*_0 # [win]
    - libnetcdf ==4.6.1=vc14_2 # [win]
    - hdf5 ==1.10.1=vc14_2 # [win]


test:
  requires:
    - nose
    - pymbar
  imports:
    - openmmtools

about:
  home: https://github.com/choderalab/openmmtools
  license: MIT License
