name: openmmtools
channels:
    - omnia
dependencies:
    - python
    - setuptools
    - openmm >=7.2
    - numpy
    - scipy
    - six
    - parmed
    - mdtraj
    - numpydoc
    - netCDF4
    - pyyaml
