name: openmmtools
channels:
    - conda-forge
    - omnia
    - omnia/label/rc
dependencies:
    - python
    - setuptools
    - cython
    - openmm >=7.3
    - numpy
    - scipy
    - six
    - parmed
    - mdtraj
    - numpydoc
    - netCDF4
    - pyyaml
